### Livros

GET http://localhost:3000/livros/664e12e83e893e40571cce1f

###

POST http://localhost:3000/livros 
content-type: application/json

{
  "titulo": "O Apanhador no Campo de Centeio",
  "preco": 45,
  "paginas": 459,
  "editora": "Maracutaia",
  "autor": "664e10d34d974494d48b2cc1"
}

###

PUT http://localhost:3000/livros/664d643f2194bf55f032ec10 
content-type: application/json

{
  "titulo": "Senhor dos aneis",
  "preco": 45,
  "paginas": 459
}

###

DELETE http://localhost:3000/livros/664e12e83e893e40571cce1f

###--------------------------------------------------------------
### Autores

GET http://localhost:3000/autores/664e10d34d974494d48b2cc2

###

POST http://localhost:3000/autores
content-type: application/json

{
  "nome": "J.D. Salinger",
  "nacionalidade": "Estados Unidos"
}

###

PUT http://localhost:3000/autores/664e109f4d974494d48b2cba 
content-type: application/json

{
  "nome": "J.D. Salinger Alterado",
  "nacionalidade": "EUA"
}

###

DELETE http://localhost:3000/autores/664e10984d974494d48b2cb8

